'use strict';

exports.__esModule = true;
var INITIATE_FORM_STATE = exports.INITIATE_FORM_STATE = 'INITIATE_FORM_STATE';
var CLEAR_FORM_STATE = exports.CLEAR_FORM_STATE = 'CLEAR_FORM_STATE';
var UPDATE_VALUE = exports.UPDATE_VALUE = 'UPDATE_VALUE';
var TOGGLE_MULTI_SELECT = exports.TOGGLE_MULTI_SELECT = 'TOGGLE_MULTI_SELECT';
var NEXT_FIELD = exports.NEXT_FIELD = 'NEXT_FIELD';
var REVERT_ACTIVE_FIELD = exports.REVERT_ACTIVE_FIELD = 'REVERT_ACTIVE_FIELD';
var SHOW_ERROR = exports.SHOW_ERROR = 'SHOW_ERROR';
var FORM_ERROR = exports.FORM_ERROR = 'FORM_ERROR';
var FIELD_ERROR = exports.FIELD_ERROR = 'FIELD_ERROR';
var NEXT_SECTION = exports.NEXT_SECTION = 'NEXT_SECTION';
var FORM_SUBMIT = exports.FORM_SUBMIT = 'FORM_SUBMIT';
var SET_DATABASE_VALUES = exports.SET_DATABASE_VALUES = 'SET_DATABASE_VALUES';